FROM node:20.9.0-alpine

ENV PORT {PORT}
ENV NODE_ENV {NODE_ENV}
ENV DB_URI {DB_URI}
ENV REQUEST_ORIGINS {REQUEST_ORIGINS}

ENV ADMIN_SECRET {ADMIN_SECRET}
ENV USER_SECRET {USER_SECRET}

ENV ADMIN_POSTMAN_PASSWORD {ADMIN_POSTMAN_PASSWORD}

ENV ADMIN_AUTH_COOKIE_NAME {ADMIN_AUTH_COOKIE_NAME}
ENV USER_AUTH_COOKIE_NAME {USER_AUTH_COOKIE_NAME}

ENV CLOUDINARY_CLOUD_NAME {CLOUDINARY_CLOUD_NAME}
ENV CLOUDINARY_API_KEY {CLOUDINARY_API_KEY}
ENV CLOUDINARY_API_SECRET {CLOUDINARY_API_SECRET}
ENV CLOUDINARY_ASSETS_FOLDER_NAME {CLOUDINARY_ASSETS_FOLDER_NAME}

ENV DUMMY_ADMIN_PASSWORD {DUMMY_ADMIN_PASSWORD}
ENV PRODUCTION_ADMIN_DOMAIN {PRODUCTION_ADMIN_DOMAIN}

WORKDIR /usr/apps/ncr-insight-api

COPY package.json .
COPY yarn.lock .

RUN yarn install --production
RUN yarn add -D @swc/cli @swc/core

COPY . .

RUN yarn build

EXPOSE 5000-10000

CMD [ "yarn", "start" ]